# -*- coding: utf-8 -*-
"""opencv01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WnZzvK9XuiL4buHTFnHQc7Ad2XrMJtHi
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

img = cv2.imread("/content/max.png")

cv2_imshow(img)

max = img.copy()

cv2_imshow(cv2.rectangle(max,(600,600),(1200,1200),(0,0,255),3))

max

max2 = max.copy()

font = cv2.FONT_HERSHEY_SIMPLEX
cv2_imshow(cv2.putText(max2, 'MAX',(600,1200),font,1,(0,0,255),3))