# -*- coding: utf-8 -*-
"""opencv02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eIvZNQwZFZeMqMgomFzbZwcqMe_gjqmZ
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

image = cv2.imread("cafe.jpg")
cv2_imshow(image)

image.shape

#criando uma img
imgCriada = np.zeros((81,81),dtype=np.uint8)
cv2_imshow(imgCriada)

#desenhando na img
imgCriada[0:10, 0:50] = 255
imgCriada[50:70, 30:50] = 255
cv2_imshow(imgCriada)

imgCriada = cv2.cvtColor(imgCriada, cv2.COLOR_GRAY2BGR)
cv2_imshow(imgCriada)
print(imgCriada.shape)

#converter png e jpg
cv2.imwrite('cafenovo.png',image)

reduzida_image=cv2.imread("cafenovo.png",cv2.IMREAD_REDUCED_COLOR_2)
print(reduzida_image.shape)
cv2_imshow(reduzida_image)

(b, g, r) = cv2.split(image)

g

image_copy = cv2.merge((b, g, r))

resized = cv2.resize(image, (2000, 500), interpolation=cv2.INTER_LINEAR)
cv2_imshow(resized)

height, width = image.shape[:2]
resized = cv2.resize(image, (2000, 500), interpolation=cv2.INTER_LINEAR)
cv2_imshow(resized)

height,witdh=image.shape[:2]

M = np.float32([[1,0,200],
                [0,1,30]])
dst_image=cv2.warpAffine(image,M,(width,height))
cv2_imshow(dst_image)

M = cv2.getRotationMatrix2D((width/2.0, height/2.0), 180, 1)
dst_image = cv2.warpAffine(image,M,(width,height))
cv2_imshow(dst_image)

